profile=gpu-hq
input-ipc-server=/tmp/iinasocket
hwdec=auto-copy
hwdec-codecs=all
hr-seek-framedrop=no
save-position-on-quit=yes
no-resume-playback

deband=yes
deband-iterations=2 # Range 1-16. Higher = better quality but more GPU usage. >5 is redundant.
deband-threshold=35 # Range 0-4096. Deband strength.
deband-range=20 # Range 1-64. Range of deband. Too high may destroy details.
deband-grain=5 # Range 0-4096. Inject grain to cover up bad banding, higher value needed for poor sources.
dither-depth=auto

volume=100 # Set volume to 100% on startup.
volume-max=100 # Set player max vol to 100%.

sub-auto=fuzzy

# glsl-shader="~~/shaders/SSimSuperRes.glsl" #Set B C parameter to Mitchell.
# scale=haasnsoft
# dscale=mitchell
# cscale=ewa_lanczossoft

# glsl-shader = "~~/shaders/Anime4K_Clamp_Highlights.glsl"
# glsl-shaders-append = "~~/shaders/Anime4K_Restore_CNN_M.glsl"
# glsl-shaders-append = "~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
# glsl-shaders-append = "~~/shaders/Anime4K_Restore_CNN_S.glsl"
# glsl-shaders-append = "~~/shaders/Anime4K_AutoDownscalePre_x2.glsl"
# glsl-shaders-append = "~~/shaders/Anime4K_AutoDownscalePre_x4.glsl"
# glsl-shaders-append = "~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"

